"""add invites

Revision ID: f020c612904a
Revises: 8047f1bedbb7
Create Date: 2026-07-03 20:42:48.651957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f020c612904a'
down_revision: Union[str, Sequence[str], None] = '8047f1bedbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_invites_created_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], name=op.f('fk_invites_used_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites'))
    )
    op.create_index('ix_invites_code_hash', 'invites', ['code_hash'], unique=True)
    op.create_index('ix_invites_created_by_user_id', 'invites', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invites_created_by_user_id', table_name='invites')
    op.drop_index('ix_invites_code_hash', table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
