import uuid
from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile, status
from fastapi.concurrency import run_in_threadpool
import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url
from urllib.parse import urlparse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from ember.db import get_db
from ember.dependencies import get_current_user
from ember.models import User
from ember.models.personal import PersonalItem, PersonalItemKind
from ember.schemas.personal import PersonalItemCreate, PersonalItemResponse, PersonalItemUpdate
from ember.config import env

router = APIRouter(prefix="/api/personal", tags=["Personal Space"])
MAX_IMAGE_BYTES = 10 * 1024 * 1024


def configure_cloudinary() -> None:
    parsed = urlparse(env["CLOUDINARY_URL"])
    if parsed.scheme != "cloudinary" or not all(
        (parsed.hostname, parsed.username, parsed.password)
    ):
        raise HTTPException(status_code=503, detail="Image uploads are not configured.")
    cloudinary.config(
        cloud_name=parsed.hostname,
        api_key=parsed.username,
        api_secret=parsed.password,
        secure=True,
    )


async def owned(db: AsyncSession, item_id: uuid.UUID, user_id: uuid.UUID) -> PersonalItem:
    item = (
        await db.execute(
            select(PersonalItem).where(PersonalItem.id == item_id, PersonalItem.user_id == user_id)
        )
    ).scalar_one_or_none()
    if item is None:
        raise HTTPException(status_code=404, detail="Not found.")
    return item


@router.get("/items")
async def list_items(
    kind: PersonalItemKind | None = Query(None),
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> list[PersonalItemResponse]:
    query = select(PersonalItem).where(PersonalItem.user_id == user.id)
    if kind:
        query = query.where(PersonalItem.kind == kind)
    return list((await db.execute(query.order_by(PersonalItem.created_at.desc()))).scalars())


@router.post("/items", status_code=status.HTTP_201_CREATED)
async def create_item(
    data: PersonalItemCreate,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> PersonalItemResponse:
    item = PersonalItem(user_id=user.id, kind=data.kind, title=data.title, data=data.data)
    db.add(item)
    await db.flush()
    await db.refresh(item)
    return item


@router.post("/vision/upload", status_code=status.HTTP_201_CREATED)
async def upload_vision_image(
    wall_id: uuid.UUID = Form(...),
    title: str = Form(default=""),
    file: UploadFile = File(...),
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> PersonalItemResponse:
    wall = await owned(db, wall_id, user.id)
    if wall.kind != PersonalItemKind.VISION or wall.data.get("type") != "wall":
        raise HTTPException(status_code=404, detail="Vision wall not found.")
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=415, detail="Only image files are supported.")
    contents = await file.read(MAX_IMAGE_BYTES + 1)
    if len(contents) > MAX_IMAGE_BYTES:
        raise HTTPException(status_code=413, detail="Image must be 10 MB or smaller.")
    if not env["CLOUDINARY_URL"]:
        raise HTTPException(status_code=503, detail="Image uploads are not configured.")
    configure_cloudinary()
    result = await run_in_threadpool(
        cloudinary.uploader.upload,
        contents,
        folder=f"ember/personal/{user.id}",
        resource_type="image",
        quality="auto",
    )
    optimized_url, _ = cloudinary_url(
        result["public_id"], fetch_format="auto", quality="auto", secure=True
    )
    item = PersonalItem(
        user_id=user.id,
        kind=PersonalItemKind.VISION,
        title=title.strip() or file.filename or "Inspiration",
        data={
            "type": "image",
            "wall_id": str(wall.id),
            "image_url": optimized_url,
            "public_id": result["public_id"],
            "width": result.get("width"),
            "height": result.get("height"),
        },
    )
    db.add(item)
    await db.flush()
    await db.refresh(item)
    return item


@router.patch("/items/{item_id}")
async def update_item(
    item_id: uuid.UUID,
    data: PersonalItemUpdate,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> PersonalItemResponse:
    item = await owned(db, item_id, user.id)
    if data.title is not None:
        item.title = data.title.strip()
    if data.data is not None:
        item.data = data.data
    await db.flush()
    # `updated_at` is generated by the database on UPDATE. Refresh it while
    # still inside the async session so response serialization never attempts
    # an implicit (and unsupported) lazy query via MissingGreenlet.
    await db.refresh(item)
    return item


@router.delete("/items/{item_id}", status_code=204)
async def delete_item(
    item_id: uuid.UUID, user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)
) -> None:
    item = await owned(db, item_id, user.id)
    if item.kind == PersonalItemKind.VISION and item.data.get("type") == "wall":
        images = list(
            (
                await db.execute(
                    select(PersonalItem).where(
                        PersonalItem.user_id == user.id,
                        PersonalItem.kind == PersonalItemKind.VISION,
                        PersonalItem.data["wall_id"].as_string() == str(item.id),
                    )
                )
            ).scalars()
        )
        if env["CLOUDINARY_URL"]:
            configure_cloudinary()
            for image in images:
                if image.data.get("public_id"):
                    await run_in_threadpool(cloudinary.uploader.destroy, image.data["public_id"])
        for image in images:
            await db.delete(image)
    public_id = item.data.get("public_id")
    if public_id and env["CLOUDINARY_URL"]:
        configure_cloudinary()
        await run_in_threadpool(cloudinary.uploader.destroy, public_id)
    await db.delete(item)
    await db.flush()
